version: "3"

silent: true

includes:
  api: 
    taskfile: ../task-library/taskfiles/api.yaml
  api-binaryops: 
    taskfile: ../task-library/taskfiles/api.yaml
    vars:
      repoUrl: 'git@github.com:vcase/voice-api.git'
      version: binaryops-v0.0.1
      package: service-template/binaryops
  api-unaryops: 
    taskfile: ../task-library/taskfiles/api.yaml
    vars:
      repoUrl: 'git@github.com:vcase/voice-api.git'
      version: unaryops-v0.0.1
      package: service-template/unaryops
  swagger: 
    taskfile: ../task-library/taskfiles/swagger.yaml

tasks:
  all:
    cmds:
      - task: gen-grpc-binaryops
      - task: gen-grpc-unaryops
      - task: swagger-ui
      - task: gen-run-server
      - task: build
  gen-grpc-binaryops:
    cmds:
      - task: api-binaryops:gen-server
  gen-grpc-unaryops:
    cmds:
      - task: api-unaryops:gen-server
  swagger-ui:
    cmds:
      - task: swagger:gen-dist
  gen-run-server:
    cmds:
      - task: api:gen-run-server
  build:
    cmds:
      - go build ./...
